# Generated by Django 5.0.7 on 2025-08-09 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='points',
        ),
        migrations.RemoveField(
            model_name='student',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='student',
            name='referred_by',
        ),
    ]
